### ISSUE TITLE
Error while loading glb

### ISSUE THREAD

**Issue by samevision** [pmndrs/react-three-offscreen#5]
Hi,

I encountered an error while migrating my scene to offscreen. The error appears if I try to load a glb via useGltf. It is glb specific since I can load some other models without any issues.

```

react-reconciler.development.js?1cbc:19034 Uncaught Error: Could not load /mesh.glb: Image is not defined)
    at eval (webpack-internal:///(app-client)/./node_modules/@react-three/fiber/dist/index-bb759d07.esm.js:1667:36)
    at _onError (webpack-internal:///(app-client)/./node_modules/three-stdlib/loaders/GLTFLoader.js:72:9)
```

Unfortunately I cannot share the model.

Any ideas?

Best

**Comment by drcmda** [comment]
i saw that, when i used gltfjsx with compression. when exporting directly out of blender it worked. im guessing it still relies on something that does not exist in the context of a worker, but would need a deeper study to see if it can be shimmed.

**Comment by drcmda** [comment]
should be semi-fixed. i shimmed the Image class which three uses to detect webp and/or avif support. im guessing that if either of those isn't supported it will fail anyway.
