### ISSUE TITLE
Passing context to the worker

### ISSUE THREAD

**Issue by snsie** [pmndrs/react-three-offscreen#7]
I'm currently working on app that would benefit from using an offscreen canvas, but the canvas depends on context that is passed using a BridgeProvider. What would be the best approach to make this work in this scenario?

Thank you!

**Comment by drcmda** [comment]
these are two different threads, they are completely separate. it is better to use this for self contained apps like the docs say but if you need to communicate you can use web broadcasts, worker postmessage, sockets, etc.
