### ISSUE TITLE
useTexture issue

### ISSUE THREAD

**Issue by samevision** [pmndrs/react-three-offscreen#9]
Hi,

is it possible anyhow to load textures inside of the worker?

The normal texture loader doesn't work since it tries to access the dom:

```
document.createElementNS is not a function
```

Best

**Comment by drcmda** [comment]
like all you're doing is useLoader(texture)? document.createElementNS doesn't exist in workers, but all these things can possibly be shimmed or faked, especially if they're not critical.

**Comment by drcmda** [comment]
should be fixed.
